Repository scottcalebc/PickleBOL, pull requests merged in 2021-02, with the labels that each got.

#10 Program 1
  pickle/Classif.java
  pickle/FileNotFoundException.java
  pickle/InvalidTokenException.java
  pickle/NumericConstantException.java
  pickle/Pickle.java
  pickle/PickleException.java
  pickle/Scanner.java
  pickle/ScannerParserException.java
  pickle/StringConstantException.java
  pickle/SubClassif.java
  pickle/SymbolTable.java
  pickle/Token.java
Labels: documentation

#12 Feature/symbol table
  .gitignore
  pickle/Classif.java
  pickle/Pickle.java
  pickle/STControl.java
  pickle/STEntry.java
  pickle/STFunction.java
  pickle/STIdentifier.java
  pickle/SubClassif.java
  pickle/SymbolTable.java
Labels: enhancement

#11 Feature/utils numeric
  pickle/Numeric.java
  pickle/NumericConstantException.java
  pickle/ResultValue.java
  pickle/Scanner.java
  pickle/Token.java
  pickle/Utility.java
Labels: enhancement

#15 Extend Scanner
  pickle/STFunction.java
  pickle/Scanner.java
  pickle/Token.java
  pickle/Utility.java
Labels: bug, documentation
